export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_PACKAGE_LIST = 'SET_PACKAGE_LIST';
export const SET_CURRENT_WIDTH = 'SET_CURRENT_WIDTH';
export const SET_MODAL_DATA = 'SET_MODAL_DATA';
export const SET_ONE_PACKAGE_LOADING = 'SET_ONE_PACKAGE_LOADING';
export const SET_ONE_PACKAGE_ERROR = 'SET_ONE_PACKAGE_ERROR';
export const SET_ONE_PACKAGE_DATA = 'SET_ONE_PACKAGE_DATA';